server:
  port: 5000
  
spring:
  main:
    banner-mode: 'off'
  application:
    name: taai-app-svc
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        generate_statistics: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://
    username: ""
    password: ""
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 100MB

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      show-details: always
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type: 
          descriptor:
            sql: INFO
    com:
      zaxxer:
        hikari: DEBUG
      taai:
        app:
          repository:
            remote:  DEBUG
  pattern:
    console: "%green(%d{yyyy-MM-dd HH:mm:ss}) %magenta([%thread]) %magenta([%marker]) %highlight(%-5level) %cyan(%logger{15}): %m%n%throwable"

feign:
  client:
    config:
      default:
        loggerLevel: full

remote:
  first-datasource:
    url: ""
  second-datasource:
    url: ""
    graphql-url: ""
    res-fmt-index: ""
    res-fmt-data: ""

